// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "deepseekAPIKey": string;
      "deepseekBaseURL": string;
      "deepseekPrompt": string;
      "mineruAPIToken": string;
      "mineruBaseURL": string;
      "mineruModelVersion": string;
    };
  }
}
